# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesite', '0002_auto_20170126_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='date',
            field=models.DateField(),
        ),
    ]
