# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesite', '0004_auto_20170128_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(default='', max_length=7)),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
