# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensesite', '0005_monthlyexpense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyexpense',
            old_name='total_expense',
            new_name='monthly_total',
        ),
    ]
