# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensesite', '0006_auto_20170129_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='monthlyexpense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expensesite.MonthlyExpense'),
        ),
    ]
